NewsWebsite/Areas/Admin/Controllers/NewsController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using NewsWebsite.Common;
using NewsWebsite.Common.Attributes;
using NewsWebsite.Data.Contracts;
using NewsWebsite.Entities;
using NewsWebsite.ViewModels.DynamicAccess;
using NewsWebsite.ViewModels.Models;
using NewsWebsite.ViewModels.News;

namespace NewsWebsite.Areas.Admin.Controllers
{
    [DisplayName("مدیریت اخبار")]
    public class NewsController : BaseController
    {
        private readonly IUnitOfWork _uw;
        private readonly IWebHostEnvironment _env;
        private readonly IMapper _mapper;
        private readonly IHttpContextAccessor _accessor;
        private const string NewsNotFound = "خبر یافت نشد.";

        public NewsController(IUnitOfWork uw, IMapper mapper, IWebHostEnvironment env , IHttpContextAccessor accessor)
        {
            _uw = uw;
            _uw.CheckArgumentIsNull(nameof(_uw));

            _env = env;
            _env.CheckArgumentIsNull(nameof(_env));

            _mapper = mapper;
            _mapper.CheckArgumentIsNull(nameof(_mapper));

            _accessor = accessor;
            _accessor.CheckArgumentIsNull(nameof(_accessor));
        }

        [HttpGet]
        [DisplayName("مشاهده")]
        [Authorize(Policy = ConstantPolicies.DynamicPermission)]
        public IActionResult Index()
        {
            return View();
        }


        [HttpGet]
        public async Task<IActionResult> GetNews(string search, string order, int offset, int limit, string sort)
        {
            var model = new PaginateModel();
            List<NewsViewModel> news;
            int total = _uw.BaseRepository<News>().CountEntities();
            if (!search.HasValue())
                search = "";
            if (limit == 0)
                limit = total;

            switch (sort)
            {
                case ("ShortTitle"):
                     if (order == "asc")
                        model.orderBy = "ShortTitle";
                    else
                        model.orderBy = "ShortTitle desc";
                    break;
                case ("بازدید"):
                    if (order == "asc")
                        model.orderBy = "NumberOfVisit";
                    else
                        model.orderBy = "NumberOfVisit desc";
                    break;
                case ("لایک"):
                    if (order == "asc")
                        model.orderBy = "NumberOfLike";
                    else
                        model.orderBy = "NumberOfLike desc";
                    break;
                case ("دیس لایک"):
                    if (order == "asc")
                        model.orderBy = "NumberOfDisLike";
                    else
                        model.orderBy = "NumberOfDisLike desc";
                    break;
                case ("تاریخ انتشار"):
                    if (order == "asc")
                        model.orderBy = "PublishDateTime";

                    else
                        model.orderBy = "PublishDateTime desc";
                    break;
                case ("نظرات"):
                    if (order == "asc")
                        model.orderBy = "NumberOfComments";

                    else
                        model.orderBy = "NumberOfComments desc";
                    break;
                default:
                    model.orderBy = "PublishDateTime";
                    break;

            }
            model.searchText = search;
            model.offset = offset;
            model.limit = limit;
            news = await _uw.NewsRepository.GetPaginateNewsAsync(model , null , null);
            if (search != "")
                total = news.Count();
            return Json(new { total = total, rows = news });
        }

        [HttpGet]
        [DisplayName("افزودن یا ویرایش")]
        [Authorize(Policy = ConstantPolicies.DynamicPermission)]
        public async Task<IActionResult> CreateOrUpdate(string newsId)
        {
            NewsViewModel newsViewModel = new NewsViewModel();
            newsViewModel.NewsCategoriesViewModel = new NewsCategoriesViewModel(await _uw.CategoryRepository.GetAllCategoriesAsync(), null);
            ViewBag.Tags = _uw._Context.Tags.Select(t => t.TagName).ToList();
            if (newsId.HasValue())
            {
                var news = await (from n in _uw._Context.News.Include(c => c.NewsCategories)
                            join w in _uw._Context.NewsTags on n.NewsId equals w.NewsId into bc
                            from bct in bc.DefaultIfEmpty()
                            join t in _uw._Context.Tags on bct.TagId equals t.TagId into cg
                            from cog in cg.DefaultIfEmpty()
                            where (n.NewsId == newsId)
                            select new NewsViewModel
                            {
                                NewsId = n.NewsId,
                                Abstract = n.Abstract,
                                Title = n.Title,
                                Description = n.Description,
                                PublishDateTime = n.PublishDateTime,
                                IsPublish = n.IsPublish,
                                ImageName = n.ImageName,
                                IsInternal = n.IsInternal,
                                NewsCategories = n.NewsCategories,
                                Url = n.Url,
                                NameOfTags = cog!=null? cog.TagName:"",
                            }).ToListAsync();

                if (news != null)
                {
                    newsViewModel = _mapper.Map<NewsViewModel>(news.FirstOrDefault());
                    if (news.FirstOrDefault().PublishDateTime > DateTime.Now)
                    {
                        newsViewModel.FuturePublish = true;
                        newsViewModel.PersianPublishDate = news.FirstOrDefault().PublishDateTime.ConvertMiladiToShamsi("yyyy/MM/dd");
                        newsViewModel.PersianPublishTime = news.FirstOrDefault().PublishDateTime.Value.TimeOfDay.ToString();
                    }
                    newsViewModel.NewsCategoriesViewModel = new NewsCategoriesViewModel(await _uw.CategoryRepository.GetAllCategoriesAsync(),news.FirstOrDefault().NewsCategories.Select(n=>n.CategoryId).ToArray());
                    newsViewModel.NameOfTags = news.Select(t => t.NameOfTags).ToArray().CombineWith(',');
                }

            }

            return View(newsViewModel);
        }

        [HttpPost]
        public async Task<IActionResult> CreateOrUpdate(NewsViewModel viewModel,string submitButton)
        {
            ViewBag.Tags = _uw._Context.Tags.Select(t => t.TagName).ToList();
            viewModel.NewsCategoriesViewModel = new NewsCategoriesViewModel(await _uw.CategoryRepository.GetAllCategoriesAsync(), viewModel.CategoryIds);
            if (!viewModel.FuturePublish)
            {
                ModelState.Remove("PersianPublishTime");
                ModelState.Remove("PersianPublishDate");
            }
            if(viewModel.NewsId.HasValue())
                ModelState.Remove("ImageFile");

            if (ModelState.IsValid)
            {
                viewModel.Url = viewModel.Url.Trim();
                if (submitButton != "ذخیره پیش نویس")
                    viewModel.IsPublish = true;

                if (viewModel.ImageFile != null)
                    viewModel.ImageName = $"news-{StringExtensions.GenerateId(10)}.jpg";

                if (viewModel.NewsId.HasValue())
                {
                    var news = _uw.BaseRepository<News>().FindByConditionAsync(n=>n.NewsId==viewModel.NewsId,null,n => n.NewsCategories,n=>n.NewsTags).Result.FirstOrDefault();
                    if (news == null)
                        ModelState.AddModelError(string.Empty, NewsNotFound);
                    else
                    {
                        if (viewModel.IsPublish && news.IsPublish == false)
                            viewModel.PublishDateTime = DateTime.Now;

                        if (viewModel.IsPublish && news.IsPublish == true)
                        {
                            if (viewModel.PersianPublishDate.HasValue())
                            {
                                var persianTimeArray = viewModel.PersianPublishTime.Split(':');
                                viewModel.PublishDateTime = viewModel.PersianPublishDate.ConvertShamsiToMiladi().Date + new TimeSpan(int.Parse(persianTimeArray[0]), int.Parse(persianTimeArray[1]), 0);
                            }
                            else
                                viewModel.PublishDateTime = news.PublishDateTime;
                        }

                        if (viewModel.ImageFile != null)
                        {
                            viewModel.ImageFile.UploadFileBase64($"{_env.WebRootPath}/newsImage/{viewModel.ImageName}");
                            FileExtensions.DeleteFile($"{_env.WebRootPath}/newsImage/{news.ImageName}");
                        }

                        else
                            viewModel.ImageName = news.ImageName;

                        if (viewModel.NameOfTags.HasValue())
                            viewModel.NewsTags = await _uw.TagRepository.InsertNewsTags(viewModel.NameOfTags.Split(','), news.NewsId);
                        else
                            viewModel.NewsTags = news.NewsTags;

                        if (viewModel.CategoryIds == null)
                            viewModel.NewsCategories = news.NewsCategories;
                        else

NewsWebsite/Areas/Admin/Controllers/TagController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using NewsWebsite.Common;
using NewsWebsite.Data.Contracts;
using NewsWebsite.Entities;
using NewsWebsite.ViewModels.DynamicAccess;
using NewsWebsite.ViewModels.Models;
using NewsWebsite.ViewModels.Tag;

namespace NewsWebsite.Areas.Admin.Controllers
{
    [DisplayName("مدیریت تگ ها")]
    public class TagController : BaseController
    {
        private readonly IUnitOfWork _uw;
        private readonly IMapper _mapper;
        private const string TagNotFound = "برچسب یافت نشد.";
        private const string TagDuplicate = "نام برچسب تکراری است.";

        public TagController(IUnitOfWork uw, IMapper mapper)
        {
            _uw = uw;
            _uw.CheckArgumentIsNull(nameof(_uw));

            _mapper = mapper;
            _mapper.CheckArgumentIsNull(nameof(_mapper));
        }
        [DisplayName("مشاهده")]
        [Authorize(Policy = ConstantPolicies.DynamicPermission)]
        public IActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public async Task<IActionResult> GetTags(string search, string order, int offset, int limit, string sort)
        {
            List<TagViewModel> tags;
            var model = new PaginateModel();
            int total = _uw.BaseRepository<Tag>().CountEntities();
            if (!search.HasValue())
                search = "";
            if (limit == 0)
                limit = total;
            switch (sort)
            {
                case ("برچسب"):
                    if (order == "asc")
                        model.orderBy = "TagName";
                    else
                        model.orderBy = "TagName Desc";
                    break;
                default:
                    model.orderBy = "TagName";
                    break;
            }
            model.searchText = search;
            model.limit = limit;
            model.offset = offset;
            tags = await _uw.TagRepository.GetPaginateTagsAsync(model);
            if (search != "")
                total = tags.Count();
            return Json(new { total = total, rows = tags });
        }

        [HttpGet]
        [DisplayName("افزودن یا ویرایش")]
        [Authorize(Policy = ConstantPolicies.DynamicPermission)]
        public async Task<IActionResult> RenderTag(string tagId)
        {
            var tagViewModel = new TagViewModel();
            if (tagId.HasValue())
            {
                var tag = await _uw.BaseRepository<Tag>().FindByIdAsync(tagId);
                if (tag != null)
                    tagViewModel = _mapper.Map<TagViewModel>(tag);
                else
                    ModelState.AddModelError(string.Empty, TagNotFound);
            }
            return PartialView("_RenderTag", tagViewModel);
        }

        [HttpPost]
        public async Task<IActionResult> CreateOrUpdate(TagViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                if (_uw.TagRepository.IsExistTag(viewModel.TagName, viewModel.TagId))
                    ModelState.AddModelError(string.Empty, TagDuplicate);
                else
                {
                    if (viewModel.TagId.HasValue())
                    {
                        var tag = await _uw.BaseRepository<Tag>().FindByIdAsync(viewModel.TagId);
                        if (tag != null)
                        {
                            _uw.BaseRepository<Tag>().Update(_mapper.Map(viewModel, tag));
                            await _uw.Commit();
                            TempData["notification"] = EditSuccess;
                        }
                        else
                            ModelState.AddModelError(string.Empty, TagNotFound);
                    }

                    else
                    {
                        viewModel.TagId = StringExtensions.GenerateId(10);
                        await _uw.BaseRepository<Tag>().CreateAsync(_mapper.Map<Tag>(viewModel));
                        await _uw.Commit();
                        TempData["notification"] = InsertSuccess;
                    }
                }
            }

            return PartialView("_RenderTag", viewModel);
        }


        [HttpGet]
        [DisplayName("حذف")]
        [Authorize(Policy = ConstantPolicies.DynamicPermission)]
        public async Task<IActionResult> Delete(string tagId)
        {
            if (!tagId.HasValue())
                ModelState.AddModelError(string.Empty, TagNotFound);
            else
            {
                var tag = await _uw.BaseRepository<Tag>().FindByIdAsync(tagId);
                if (tag == null)
                    ModelState.AddModelError(string.Empty, TagNotFound);
                else
                    return PartialView("_DeleteConfirmation", tag);
            }
            return PartialView("_DeleteConfirmation");
        }


        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(Tag model)
        {
            if (model.TagId == null)
                ModelState.AddModelError(string.Empty, TagNotFound);
            else
            {
                var tag = await _uw.BaseRepository<Tag>().FindByIdAsync(model.TagId);
                if (tag == null)
                    ModelState.AddModelError(string.Empty, TagNotFound);
                else
                {
                    _uw.BaseRepository<Tag>().Delete(tag);
                    await _uw.Commit();
                    TempData["notification"] = DeleteSuccess;
                    return PartialView("_DeleteConfirmation", tag);
                }
            }
            return PartialView("_DeleteConfirmation");
        }


        [HttpPost, ActionName("DeleteGroup")]
        [DisplayName("حذف گروهی")]
        [Authorize(Policy = ConstantPolicies.DynamicPermission)]
        public async Task<IActionResult> DeleteGroupConfirmed(string[] btSelectItem)
        {
            if (btSelectItem.Count() == 0)
                ModelState.AddModelError(string.Empty, "هیچ برچسبی برای حذف انتخاب نشده است.");
            else
            {
                foreach (var item in btSelectItem)
                {
                    var tag = await _uw.BaseRepository<Tag>().FindByIdAsync(item);
                    _uw.BaseRepository<Tag>().Delete(tag);
                }
                await _uw.Commit();
                TempData["notification"] = "حذف گروهی اطلاعات با موفقیت انجام شد.";
            }

            return PartialView("_DeleteGroup");
        }
    }
}

NewsWebsite/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Start your development with a Dashboard for Bootstrap 4.">
    <meta name="author" content="Creative Tim">
    <title>پنل مدیریت سایت خبری</title>
    <!-- Favicon -->
    <link href="/assets/img/favicon.png" rel="icon" type="image/png">
    <!-- Icons -->
    <link href="/assets/vendor/nucleo/css/nucleo.css" rel="stylesheet">
    <link href="/assets/vendor/fontawesome/fontawesome-free/css/all.min.css" rel="stylesheet">
    <!-- Argon CSS -->
    <link type="text/css" href="/assets/css/argon.css?v=1.0.0" rel="stylesheet">
    <script src="/assets/vendor/jquery/dist/jquery.min.js"></script>
    <script src="/assets/vendor/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/CacheFiles/js/Ajax.js"></script>
    <!-- Loading -->
    <link href="~/CacheFiles/lib/Loading/css/preloader.css" rel="stylesheet" />
    <script src="~/CacheFiles/lib/Loading/js/jquery.preloader.min.js"></script>

    <!-- Sweetalert2 -->
    <link href="~/lib/sweetalert2/dist/sweetalert2.min.css" rel="stylesheet" />
    <link href="~/CacheFiles/lib/sweetalert2/dist/sweetalert2.min.css" rel="stylesheet" />
    <script src="~/lib/sweetalert2/dist/sweetalert2.min.js"></script>
    <script src="~/CacheFiles/lib/sweetalert2/dist/sweetalert2.min.js"></script>

    <!-- DateTimePicker -->
    <link href="~/lib/bootstrap.datetimepicker/css/jquery.md.bootstrap.datetimepicker.style.css" rel="stylesheet" />
    <script src="~/lib/bootstrap.datetimepicker/js/jquery.md.bootstrap.datetimepicker.js"></script>

    <link href="~/css/bootstrap-fileinput.css" rel="stylesheet" />
    <script src="~/js/bootstrap-fileinput.min.js"></script>

    <!-- Bootstrap Table -->
    <link href="/assets/vendor/bootstrap-table/dist/bootstrap-table.min.css" rel="stylesheet" />
    <link href="~/CacheFiles/assets/vendor/bootstrap-table/dist/bootstrap-table.css" rel="stylesheet" />
    <script src="/assets/vendor/bootstrap-table/dist/bootstrap-table.js"></script>
    <script src="~/CacheFiles/assets/vendor/bootstrap-table/dist/bootstrap-table.js"></script>
    <script src="~/assets/vendor/bootstrap-table/dist/extensions/export/tableExport.js"></script>
    <script src="~/CacheFiles/assets/vendor/bootstrap-table/dist/extensions/export/tableExport.js"></script>
    <script src="~/assets/vendor/bootstrap-table/dist/bootstrap-table-locale-all.js"></script>
    <script src="~/CacheFiles/assets/vendor/bootstrap-table/dist/bootstrap-table-locale-all.js"></script>
    <script src="~/assets/vendor/bootstrap-table/dist/extensions/export/bootstrap-table-export.min.js"></script>
    <script src="~/CacheFiles/assets/vendor/bootstrap-table/dist/extensions/export/bootstrap-table-export.min.js"></script>
</head>
<body>
    <!-- Sidenav -->
    <nav class="navbar navbar-vertical fixed-left navbar-expand-md navbar-light bg-white" id="sidenav-main">
        <div class="container-fluid">
            <!-- Toggler -->
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#sidenav-collapse-main" aria-controls="sidenav-main" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <!-- Brand -->
            <a class="navbar-brand pt-0" href="./index.html">
                <img src="/assets/img/Logo.png" class="navbar-brand-img" alt="...">
                پنل مدیریت میزفا
            </a>
            <!-- User -->
            <ul class="nav align-items-center d-md-none">
                <li class="nav-item dropdown">
                    <a class="nav-link" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <div class="media align-items-center">
                            <span class="avatar avatar-sm rounded-circle">
                                <img alt="Image placeholder" src="/assets/img/avatar.jpg">
                            </span>
                        </div>
                    </a>
                    <div class="dropdown-menu dropdown-menu-arrow dropdown-menu-right">
                        <a href="./examples/profile.html" class="dropdown-item">
                            <i class="ni ni-single-02"></i>
                            <span>نمایه من</span>
                        </a>
                        <div class="dropdown-divider"></div>
                        <a href="#!" class="dropdown-item">
                            <i class="ni ni-user-run"></i>
                            <span>خروج</span>
                        </a>
                    </div>
                </li>
            </ul>
            <!-- Collapse -->
            <div class="collapse navbar-collapse" id="sidenav-collapse-main">
                <!-- Collapse header -->
                <div class="navbar-collapse-header d-md-none">
                    <div class="row">
                        <div class="col-9 collapse-brand">
                            <a href="./index.html">
                                <img src="~/assets/img/Logo.png"> پنل مدیریت میزفا
                            </a>
                        </div>
                        <div class="col-3 collapse-close">
                            <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#sidenav-collapse-main" aria-controls="sidenav-main" aria-expanded="false" aria-label="Toggle sidenav">
                                <span></span>
                                <span></span>
                            </button>
                        </div>
                    </div>
                </div>
                <!-- Form -->

                <hr class="my-3">
                <!-- Navigation -->
                @await Html.PartialAsync("_AdminMenu")
            </div>
        </div>
    </nav>
    <!-- Main content -->
    <div class="main-content">
        @RenderBody()
        <footer class="footer container-fluid">
            <div class="row align-items-center justify-content-xl-between">
                <div class="col-xl-6">
                </div>
            </div>
        </footer>
    </div>

    <script src="/assets/js/argon.js?v=1.0.0"></script>
    @RenderSection("Scripts", false)

</body>
</html>

NewsWebsite/Views/Shared/_AdminLogin.cshtml
@using NewsWebsite.Services.Contracts
@using NewsWebsite.Common
@using NewsWebsite.Data.Contracts
@inject IApplicationUserManager userManager
@inject ICommentRepository commentRepository

@{ 
    var user = await userManager.GetUserAsync(User);
}
<style>
    .notification {
        display: inline-block;
        position: relative;
        padding: 0.2em 0.4em;
        background: #f5365c;
        border-radius: 0.2em;
        font-size: 1em;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.2);
    }

        .notification.notify::before {
            animation: ring 1.5s ease;
        }

        .notification::before {
            display: block;
            content: "\f086";
            font-family: "FontAwesome";
            transform-origin: top center;
        }

        .notification::before, .notification::after {
            color: #fff;
            text-shadow: 0 1px 3px rgba(0, 0, 0, 0.3);
        }

        .notification.show-count::after {
            transform: scale(1);
            opacity: 1;
        }

        .notification::after {
            font-family: Arial;
            font-size: 0.6em;
            font-weight: 700;
            position: absolute;
            top: -10px;
            right: -10px;
            padding: 2px 4px;
            line-height: 100%;
            border: 2px #fff solid;
            border-radius: 60px;
            background: #3498db;
            opacity: 0;
            content: attr(data-count);
            opacity: 0;
            transform: scale(0.5);
            transition: transform, opacity;
            transition-duration: 0s, 0s;
            transition-timing-function: ease, ease;
            transition-duration: 0s, 0s;
            transition-timing-function: ease, ease;
            transition-duration: 0.3s;
            transition-timing-function: ease-out;
        }

        .notification::before, .notification::after {
            color: #fff;
            text-shadow: 0 1px 3px rgba(0, 0, 0, 0.3);
        }
</style>
<ul class="navbar-nav align-items-center d-none d-md-flex">
    <li>
        <a href="/Admin/Comments/Index?isConfirm=false" class="notification notify show-count ml-4" data-count="@commentRepository.UnConfiremCommentCount()"></a>
    </li>
    <li class="nav-item dropdown">
        <a class="nav-link pr-0" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <div class="media align-items-center">
                <span class="avatar avatar-sm rounded-circle">
                    @if (user.Image.HasValue())
                    {
                        <img alt="Image placeholder" src="~/avatars/@user.Image">
                    }

                    else
                    {
                        <img alt="Image placeholder" src="~/assets/img/UserPic.png">
                    }

                </span>
                <div class="media-body ml-2 d-none d-lg-block">
                    <span class="mb-0 text-sm  font-weight-bold">@user.FirstName @user.LastName</span>
                </div>
            </div>
        </a>
        <div class="dropdown-menu dropdown-menu-arrow dropdown-menu-right">
            <a class="dropdown-item" asp-action="Profile" asp-controller="Manage" asp-route-userId="@user.Id">
                <i class="ni ni-single-02"></i>
                <span>نمایه من</span>
            </a>
            <div class="dropdown-divider"></div>
            <form asp-action="SignOut" asp-controller="Manage" asp-area="Admin">
                <button type="submit" class="btn btn-link m-0 font-weight-normal dropdown-item">
                    <i class="ni ni-user-run"></i> خروج
                </button>
            </form>
        </div>
    </li>
</ul>

NewsWebsite/Views/Shared/_AdminMenu.cshtml
@using NewsWebsite.Common;
@addTagHelper*,NewsWebsite
<ul class="navbar-nav">
    <li class="nav-item">
            <a class="nav-link" asp-action="Index" asp-controller="Dashboard">
                <i class="ni ni-tv-2 text-primary"></i> داشبورد
            </a>
    </li>
    <li class="nav-item">
        <security-trimming asp-action="Index" asp-controller="Category" asp-area="Admin">
            <a class="nav-link" asp-action="Index" asp-controller="Category">
                <i class="ni ni-bullet-list-67 text-red"></i> مدیریت دسته بندی ها
            </a>
        </security-trimming>
    </li>
    <li class="nav-item">
        <security-trimming asp-action="Index" asp-controller="Tag" asp-area="Admin">
            <a class="nav-link" asp-action="Index" asp-controller="Tag">
                <i class="ni ni-bullet-list-67 text-red"></i> مدیریت برچسب ها
            </a>
        </security-trimming>
    </li>
    <li class="nav-item">
        <security-trimming asp-action="Index" asp-controller="News" asp-area="Admin">
            <a class="nav-link" asp-action="Index" asp-controller="News">
                <i class="ni ni-folder-17 text-blue"></i> مدیریت اخبار
            </a>
        </security-trimming>
    </li>

    <li class="nav-item">
        <security-trimming asp-action="Index" asp-controller="RoleManager" asp-area="Admin">
            <a class="nav-link" asp-action="Index" asp-controller="RoleManager">
                <i class="fa fa-user text-pink"></i> مدیریت نقش ها
            </a>
        </security-trimming>
    </li>
    <li class="nav-item">
        <security-trimming asp-action="Index" asp-controller="UserManager" asp-area="Admin">
            <a class="nav-link" asp-action="Index" asp-controller="UserManager">
                <i class="fa fa-users text-yellow"></i> مدیریت کاربران
            </a>
        </security-trimming>
    </li>
    <li class="nav-item">
        <security-trimming asp-action="Index" asp-controller="Video" asp-area="Admin">
            <a class="nav-link" asp-action="Index" asp-controller="Video">
                <i class="fa fa-video text-primary"></i> مدیریت ویدیوها
            </a>
        </security-trimming>
    </li>
    <li class="nav-item">
        <security-trimming asp-action="Index" asp-controller="Comments" asp-area="Admin">
            <a class="nav-link" asp-action="Index" asp-controller="Comments">
                <i class="fa fa-comments text-info"></i> مدیریت نظرات
            </a>
        </security-trimming>

    </li>
    <li class="nav-item">
        <security-trimming asp-action="Index" asp-controller="Newsletter" asp-area="Admin">
            <a class="nav-link" asp-action="Index" asp-controller="Newsletter">
                <i class="ni ni-notification-70 text-danger"></i> مدیریت خبرنامه
            </a>
        </security-trimming>
    </li>

    <li class="nav-item">
        <a class="nav-link" asp-action="ChangePassword" asp-controller="Manage">
            <i class="ni ni-key-25 text-info"></i> تغییر کلمه عبور
        </a>
    </li>
    <li class="nav-item">
        <security-trimming asp-action="Index" asp-controller="SiteSetting" asp-area="Admin">
            <a class="nav-link" asp-action="Index" asp-controller="SiteSetting">
                <i class="ni ni-settings-gear-65 text-suceess"></i> تنظیمات سایت
            </a>
        </security-trimming>
    </li>
    <li class="nav-item">
        <a class="nav-link" asp-action="Profile" asp-controller="Manage" asp-route-userId="@User.Identity.GetUserId()">
            <i class="ni ni-circle-08 text-pink"></i> نمایه من
        </a>
    </li>
</ul>