NewsWebsite/Areas/Admin/Controllers/UserManagerController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using NewsWebsite.Common;
using NewsWebsite.Data.Contracts;
using NewsWebsite.Entities.identity;
using NewsWebsite.Services.Contracts;
using NewsWebsite.ViewModels.DynamicAccess;
using NewsWebsite.ViewModels.Models;
using NewsWebsite.ViewModels.UserManager;

namespace NewsWebsite.Areas.Admin.Controllers
{
    [DisplayName("مدیریت کاربران")]
    public class UserManagerController : BaseController
    {
        private readonly IApplicationUserManager _userManager;
        private readonly IApplicationRoleManager _roleManager;
        private readonly IMapper _mapper;
        private readonly IWebHostEnvironment _env;
        //private readonly IUnitOfWork _uw;
        private const string UserNotFound = "کاربر یافت نشد.";
        public UserManagerController(IApplicationUserManager userManager, IMapper mapper, IApplicationRoleManager roleManager, IWebHostEnvironment env)
        {
            _userManager = userManager;
            _userManager.CheckArgumentIsNull(nameof(_userManager));

            _mapper = mapper;
            _mapper.CheckArgumentIsNull(nameof(_mapper));

            _roleManager = roleManager;
            _roleManager.CheckArgumentIsNull(nameof(_roleManager));

            _env = env;
            _env.CheckArgumentIsNull(nameof(_env));
        }

        [HttpGet]
        [DisplayName("مشاهده")]
        [Authorize(Policy = ConstantPolicies.DynamicPermission)]
        public IActionResult Index()
        {
            return View();
        }
        public async Task<JsonResult> GetUsers(string search, string order, int offset, int limit, string sort)
        {
            try
            {
                List<UsersViewModel> allUsers;
                var model = new PaginateModel();
                int total = _userManager.Users.Count();
                if (string.IsNullOrWhiteSpace(search))
                    search = "";
                if (limit == 0)
                    limit = total;
                switch (sort)
                {
                    case ("نام"):
                        if (order == "asc")
                            model.orderBy = "FirstName";
                        else
                            model.orderBy = "FirstName Desc";
                        break;
                    case ("نام خانوادگی"):
                        if (order == "asc")
                            model.orderBy = "LastName";
                        else
                            model.orderBy = "LastName Desc";
                        break;
                    case ("ایمیل"):
                        if (order == "asc")
                            model.orderBy = "Email";
                        else
                            model.orderBy = "Email Desc";
                        break;
                    case ("نام کاربری"):
                        if (order == "asc")
                            model.orderBy = "UserName";
                        else
                            model.orderBy = "UserName Desc";
                        break;
                    case ("تاریخ عضویت"):
                        if (order == "asc")
                            model.orderBy = "RegisterDateTime";
                        else
                            model.orderBy = "RegisterDateTime Desc";
                        break;
                    default:
                        model.orderBy = "RegisterDateTime";
                        break;
                }
                model.searchText = search;
                model.limit = limit;
                model.offset = offset;
                allUsers = await _userManager.GetPaginateUsersAsync(model);
                if (search != "")
                    total = allUsers.Count();
                return Json(new { total = total, rows = allUsers });
            }
            catch(Exception ex)
            {
                return new JsonResult(ex.Message) ;
            }
        }

        [HttpGet]
        [DisplayName("افزودن یا ویرایش")]
        [Authorize(Policy = ConstantPolicies.DynamicPermission)]
        public async Task<IActionResult> RenderUser(int? userId)
        {
            var user = new UsersViewModel();
            ViewBag.Roles = _roleManager.GetAllRoles();

            if (userId != null)
            {
                user = _mapper.Map<UsersViewModel>(await _userManager.FindUserWithRolesByIdAsync((int)userId));
                user.PersianBirthDate = user.BirthDate.ConvertMiladiToShamsi("yyyy/MM/dd");
            }

            return PartialView("_RenderUser", user);
        }

        [HttpPost]
        public async Task<IActionResult> CreateOrUpdate(UsersViewModel viewModel)
        {
            try
            {
                ViewBag.Roles = _roleManager.GetAllRoles();
                if (viewModel.Id != null)
                {
                    ModelState.Remove("Password");
                    ModelState.Remove("ConfirmPassword");
                    ModelState.Remove("ImageFile");
                }

                if (ModelState.IsValid)
                {
                    IdentityResult result;
                    if (viewModel.ImageFile != null)
                        viewModel.Image = _userManager.CheckAvatarFileName(viewModel.ImageFile.FileName);
                    viewModel.Roles = new List<UserRole> { new UserRole { RoleId = (int)viewModel.RoleId } };
                    viewModel.BirthDate = viewModel.PersianBirthDate.ConvertShamsiToMiladi();

                    if (viewModel.Id != null)
                    {
                        var user = await _userManager.FindByIdAsync(viewModel.Id.ToString());
                        user.FirstName = viewModel.FirstName;
                        user.Roles = viewModel.Roles;
                        user.BirthDate = viewModel.BirthDate;
                        user.LastName = viewModel.LastName;
                        user.Email = viewModel.Email;
                        user.UserName = viewModel.UserName;
                        user.Gender = viewModel.Gender.Value;
                        user.PhoneNumber = viewModel.PhoneNumber;
                        user.Bio = viewModel.Bio;
                        var userRoles = await _userManager.GetRolesAsync(user);
                        if (viewModel.ImageFile != null)
                        {
                            await viewModel.ImageFile.UploadFileAsync($"{_env.WebRootPath}/avatars/{viewModel.Image}");
                            FileExtensions.DeleteFile($"{_env.WebRootPath}/avatars/{user.Image}");
                            user.Image = viewModel.Image;
                        }
                        result = await _userManager.RemoveFromRolesAsync(user, userRoles);
                        if (result.Succeeded)
                            result = await _userManager.UpdateAsync(user);
                    }

                    else
                    {
                        await viewModel.ImageFile.UploadFileAsync($"{_env.WebRootPath}/avatars/{viewModel.Image}");
                        viewModel.EmailConfirmed = true;
                        result = await _userManager.CreateAsync(_mapper.Map<User>(viewModel), viewModel.Password);
                    }

                    if (result.Succeeded)
                        TempData["notification"] = OperationSuccess;
                    else
                        ModelState.AddErrorsFromResult(result);
                }

                return PartialView("_RenderUser", viewModel);
            }
            catch (Exception ex)
            {
                return PartialView("_RenderUser", viewModel);
            }
        }

        [HttpGet]
        [DisplayName("حذف")]
        [Authorize(Policy = ConstantPolicies.DynamicPermission)]
        public async Task<IActionResult> Delete(string userId)
        {
            if (!userId.HasValue())
                ModelState.AddModelError(string.Empty,UserNotFound);
            else
            {
                var user = await _userManager.FindByIdAsync(userId.ToString());
                if (user == null)
                    ModelState.AddModelError(string.Empty,UserNotFound);
                else
                    return PartialView("_DeleteConfirmation", user);
            }
            return PartialView("_DeleteConfirmation");
        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(User model)
        {
            var user = await _userManager.FindByIdAsync(model.Id.ToString());
            if (user == null)
                ModelState.AddModelError(string.Empty, UserNotFound);
            else
            {
                var result = await _userManager.DeleteAsync(user);
                if (result.Succeeded)
                {
                    FileExtensions.DeleteFile($"{_env.WebRootPath}/avatars/{user.Image}");
                    TempData["notification"] = DeleteSuccess;
                    return PartialView("_DeleteConfirmation",user);
                }
                else
                    ModelState.AddErrorsFromResult(result);
            }

            return PartialView("_DeleteConfirmation");
        }

        [HttpPost, ActionName("DeleteGroup")]
        [DisplayName("حذف گروهی")]
        [Authorize(Policy = ConstantPolicies.DynamicPermission)]
        public async Task<IActionResult> DeleteGroupConfirmed(string[] btSelectItem)
        {
            if (btSelectItem.Count() == 0)
                ModelState.AddModelError(string.Empty, "هیچ کاربری برای حذف انتخاب نشده است.");
            else
            {
                foreach (var item in btSelectItem)
                {

NewsWebsite/Areas/Admin/Views/UserManager/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


<div id="modal-placeholder"></div>
<nav class="navbar navbar-top navbar-expand-md navbar-dark" id="navbar-main">
    <div class="container-fluid">
        <!-- Brand -->
        <ul class="nav nav-sitemap justify-content-center justify-content-xl-end">
            <li>
                <a class="h4 mb-0 text-white d-lg-inline-block" href="./index.html"> داشبورد </a>
            </li>
            <li class="pr-2 pl-2">
                <i class="fa fa-angle-left text-white align-middle"></i>
            </li>
            <li>
                <a class="h4 mb-0 text-white d-lg-inline-block" href="./index.html">مدیریت کاربران</a>
            </li>

        </ul>

        <!-- User -->
        @await Html.PartialAsync("_AdminLogin")
    </div>
</nav>
<!-- Header -->
<div class="header bg-gradient-primary pb-4 pt-5 pt-md-8">
</div>

<div class="container-fluid mt--7">
    <div class="row mt-5">
        <div class="card shadow w-100">
            <div class="card-header font_Vazir_Medium">
                مدیریت کاربران
            </div>
            <div class="card-body">
                <form asp-area="Admin" asp-controller="UserManager">
                    @await Html.PartialAsync("_UserTable")
                </form>
            </div>
        </div>
    </div>
</div>

NewsWebsite/Areas/Admin/Views/UserManager/ResetPassword.cshtml
@model NewsWebsite.ViewModels.UserManager.ResetPasswordViewModel
@{
    ViewData["Title"] = "ResetPassword";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<nav class="navbar navbar-top navbar-expand-md navbar-dark" id="navbar-main">
    <div class="container-fluid">
        <!-- Brand -->
        <ul class="nav nav-sitemap justify-content-center justify-content-xl-end">
            <li>
                <a class="h4 mb-0 text-white d-lg-inline-block" href="./index.html"> داشبورد </a>
            </li>
            <li class="pr-2 pl-2">
                <i class="fa fa-angle-left text-white align-middle"></i>
            </li>
            <li>
                <a class="h4 mb-0 text-white d-lg-inline-block" href="#">بازنشانی کلمه عبور</a>
            </li>

        </ul>

        <!-- User -->
        @await Html.PartialAsync("_AdminLogin")
    </div>
</nav>
<!-- Header -->
<div class="header bg-gradient-primary pb-4 pt-5 pt-md-8">
</div>

<div class="container-fluid mt--7">
    <div class="row mt-5">
        <div class="card shadow w-100">
            <div class="card-header font_Vazir_Medium">
                بازنشانی کلمه عبور
            </div>
            <div class="card-body">
                <form asp-action="ResetPassword" method="post">
                    <div class="card-body">
                        @if (ViewBag.AlertSuccess != null)
                        {
                            <div class="alert alert-success alert-dismissable mb-4">
                                @ViewBag.AlertSuccess
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                        }
                        <div class="row">
                            <div class="col-md-6 border-left">
                                <div asp-validation-summary="ModelOnly" class="alert alert-danger">

                                </div>
                                <div class="row">
                                    <input type="hidden" asp-for="userId" />

                                    <div class="form-group col-md-12">
                                        <label asp-for="Email"></label>
                                        <input asp-for="Email" class="form-control" disabled />
                                        <span asp-validation-for="Email" class="text-danger"></span>
                                    </div>

                                    <div class="form-group col-md-12">
                                        <label asp-for="NewPassword"></label>
                                        <input asp-for="NewPassword" class="form-control" type="password" />
                                        <span asp-validation-for="NewPassword" class="text-danger"></span>
                                    </div>
                                </div>
                                <div class="form-group col-md-12">
                                    <button type="submit" class="btn btn-primary float-left">بازنشانی</button>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="alert p-0">
                                    <ul>
                                        <li>"کلمه عبور باید حداقل شامل یک کاراکتر عدد ('0'-'9') باشد."</li>
                                        <li>"کلمه عبور باید حداقل شامل یکی از کاراکترهای حرفی ('a'-'z') باشد."</li>
                                        <li>"کلمه عبور باید حداقل شامل یک حرف بزرگ ('A'-'Z') باشد."</li>
                                        <li>"کلمه عبور باید حداقل شامل 6 کاراکتر باشد." </li>
                                    </ul>
                                </div>
                            </div>
                        </div>

                    </div>
                    
                </form>
            </div>
        </div>
    </div>
</div>

NewsWebsite/Areas/Admin/Views/UserManager/_DeleteConfirmation.cshtml
@model  NewsWebsite.Entities.identity.User

<div class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h3 id="modal-title">حذف اطلاعات</h3>
                    <button type="button" class="close btn-link" data-dismiss="modal" aria-hidden="true">×</button>
                </div>
                <div class="modal-body clearfix">
                    @if (Model==null)
                    {
                        <div asp-validation-summary="ModelOnly" class="alert alert-danger"></div>
                    }
                    else
                    {
                        <h4>آیا شما می خواهید  @Model.FirstName  @Model.LastName را از لیست کاربران حذف کنید ؟</h4>
                        <form asp-action="Delete">
                            <input name="IsValid" type="hidden" value="True" />
                            <input type="hidden" asp-for="Id"/>
                        </form>
                    }
                </div>

                <div class="modal-footer">
                    @if (Model != null)
                    {
                        <button type="submit" class="btn btn-sm btn-labeled btn-success" data-save="modal">
                            بله
                        </button>
                    }
                    <button type="button" class="btn btn-sm btn-labeled  btn-danger  mr-1" data-dismiss="modal">
                        @(Model != null ? "خیر" : "بستن")
                    </button>

                </div>
            </div>
        </div>
</div>

NewsWebsite/Areas/Admin/Views/UserManager/_RenderUser.cshtml
@model NewsWebsite.ViewModels.UserManager.UsersViewModel
@using NewsWebsite.Entities.identity.Enums;
@using NewsWebsite.Entities.identity;

<style>
    .modal-dialog {
        max-width: 800px !important;
    }
</style>

<div class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">

                @if (Model.Id != null)
                {
                    <h3 id="modal-title">ویرایش اطلاعات کاربر</h3>
                }
                else
                {
                    <h3 id="modal-title">افزودن کاربر جدید</h3>
                }
                <button type="button" class="close btn-link" data-dismiss="modal" aria-hidden="true">×</button>
            </div>
            <div class="modal-body clearfix" style="max-height: 450px;overflow-y: auto;">
                <form asp-action="CreateOrUpdate">
                    @if (ViewData.ModelState.IsValid.ToString() == "False")
                    {
                        <div asp-validation-summary="ModelOnly" class="alert alert-danger mb-4"></div>
                    }

                    <input name="IsValid" type="hidden" value="@ViewData.ModelState.IsValid.ToString()" />
                    <input type="hidden" asp-for="Id" />

                    <div class="row mt-2 mb-2">
                        <div class="col-md-4 border-left">
                            <div class="col-md-12 border-bottom text-center">
                                <p>
                                    تصویر پروفایل
                                </p>
                                <div class="fileinput fileinput-new" data-provides="fileinput">
                                    <div class="fileinput-new thumbnail" style="height: 150px;">
                                        @if (Model.Image != null)
                                        {
                                            <input type="hidden" asp-for="Image" value="@Model.Image" />
                                            <img src="~/avatars/@Model.Image" />
                                        }
                                        else
                                        {
                                            <img src="~/assets/img/UserPic.png" />
                                        }
                                    </div>
                                    <div class="fileinput-preview fileinput-exists thumbnail" style="height:200px"> </div>
                                    <div>
                                        <span class="btn default btn-file">
                                            <span class="fileinput-new btn btn-success"> انتخاب کنید </span>
                                            <span class="fileinput-exists btn btn-default"> تغییر عکس </span>
                                            <input type="file" asp-for="ImageFile" accept=".jpg, .png, .jpeg, .gif, .tif, .tiff, .JPG" />
                                        </span>
                                        <a href="javascript:;" class="btn btn-danger fileinput-exists" data-dismiss="fileinput"> حذف </a>
                                    </div>
                                    <span asp-validation-for="ImageFile" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="col-md-12">
                                <p class="mt-3">اختصاص نقش به کاربر</p>
                                @foreach (var item in ViewBag.Roles as List<Role>)
                                {
                                    <label class="col-md-8" style="vertical-align:20px;">@item.Name</label>
                                    <label class="custom-toggle">
                                        @if (Model.Roles != null)
                                        {
                                            if (Model.Roles.Select(r => r.RoleId).Contains(item.Id))
                                            {
                                                <input type="radio" value="@item.Id" asp-for="RoleId" checked />
                                            }
                                            else
                                            {
                                                <input type="radio" value="@item.Id" asp-for="RoleId" />
                                            }
                                        }

                                        else
                                        {
                                            <input type="radio" value="@item.Id" asp-for="RoleId" />
                                        }
                                        <span class="custom-toggle-slider rounded-circle"></span>
                                    </label>
                                    <span class="clearfix"></span>
                                }

                                <span asp-validation-for="RoleId" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-8">
                            <div class="form-group row">
                                <div class="col-md-3">
                                    <label asp-for="UserName" class="control-label"></label>
                                </div>
                                <div class="col-md-9">
                                    <input asp-for="UserName" class="form-control" />
                                    <span asp-validation-for="UserName" class="text-danger"></span>
                                </div>
                            </div>
                            @if (!Model.Id.HasValue)
                            {
                                <div class="form-group row">
                                    <div class="col-md-3">
                                        <label asp-for="Password" class="control-label"></label>
                                    </div>
                                    <div class="col-md-9">
                                        <input asp-for="Password" class="form-control" />
                                        <span asp-validation-for="Password" class="text-danger"></span>
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <div class="col-md-3">
                                        <label asp-for="ConfirmPassword" class="control-label"></label>
                                    </div>
                                    <div class="col-md-9">
                                        <input asp-for="ConfirmPassword" class="form-control" />
                                        <span asp-validation-for="ConfirmPassword" class="text-danger"></span>
                                    </div>
                                </div>
                            }

                            <div class="form-group row">
                                <div class="col-md-3">
                                    <label asp-for="Email" class="control-label"></label>
                                </div>
                                <div class="col-md-9">
                                    <input asp-for="Email" class="form-control" />
                                    <span asp-validation-for="Email" class="text-danger"></span>
                                </div>
                            </div>

                            <div class="form-group row">
                                <div class="col-md-3">
                                    <label asp-for="FirstName" class="control-label"></label>
                                </div>
                                <div class="col-md-9">
                                    <input asp-for="FirstName" class="form-control" />
                                    <span asp-validation-for="FirstName" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="form-group row">
                                <div class="col-md-3">
                                    <label asp-for="LastName" class="control-label"></label>
                                </div>
                                <div class="col-md-9">
                                    <input asp-for="LastName" class="form-control" />
                                    <span asp-validation-for="LastName" class="text-danger"></span>
                                </div>
                            </div>

                            <div class="form-group row">
                                <div class="col-md-3">
                                    <label asp-for="Gender" class="control-label"></label>
                                </div>
                                <div class="col-md-9">
                                    <div class="row">
                                        <div class="col-md-4 custom-control custom-radio mb-3">
                                            <input asp-for="Gender" value="@GenderType.male" class="custom-control-input" id="customRadio1" type="radio">
                                            <label class="custom-control-label" for="customRadio1">مرد</label>
                                        </div>
                                        <div class="col-md-4 custom-control custom-radio mb-3">
                                            <input asp-for="Gender" value="@GenderType.famale" class="custom-control-input" id="customRadio2" type="radio">
                                            <label class="custom-control-label" for="customRadio2">زن</label>
                                        </div>
                                    </div>
                                    <span asp-validation-for="Gender" class="text-danger"></span>
                                </div>
                            </div>

                            <div class="form-group row">
                                <div class="col-md-3">
                                    <label asp-for="PhoneNumber" class="control-label"></label>
                                </div>
                                <div class="col-md-9">
                                    <input asp-for="PhoneNumber" class="form-control" />
                                    <span asp-validation-for="PhoneNumber" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="form-group row">
                                <div class="col-md-3">
                                    <label asp-for="Bio" class="control-label"></label>
                                </div>
                                <div class="col-md-9">
                                    <textarea asp-for="Bio" class="form-control" />
                                    <span asp-validation-for="Bio" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="form-group row">
                                <div class="col-md-3">
                                    <label asp-for="PersianBirthDate" class="control-label"></label>
                                </div>
                                <div class="col-md-9">
                                    <div class="input-group">
                                        <div class="input-group-prepend">
                                            <span class="input-group-text cursor-pointer" id="BirthDate">
                                                <i class="fa fa-calendar"></i>
                                            </span>
                                        </div>
                                        <input asp-for="PersianBirthDate" class="form-control" id="InputBirthDate" style="direction:ltr" />

                                    </div>
                                </div>

                                <span asp-validation-for="PersianBirthDate" class="text-danger"></span>
                            </div>
                            <script>
                                $("#BirthDate").MdPersianDateTimePicker({
                                    targetTextSelector: "#InputBirthDate",
                                    placement: 'top',
                                });
                            </script>
                        </div>
                    </div>
                </form>
            </div>

            <div class="modal-footer">
                <button type="button" class="btn btn-sm btn-secondary" data-dismiss="modal">بستن</button>
                @if (Model.Id != null)
                {
                    <button type="submit" class="btn btn-sm btn-labeled btn-success mr-1" data-save="modal">
                        ذخیره تغییرات
                    </button>
                }
                else
                {
                    <button type="submit" class="btn btn-sm btn-labeled btn-success mr-1" data-save="modal">
                        افزودن اطلاعات
                    </button>
                }
            </div>
        </div>
    </div>
</div>